deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  local_dir: _site
  repo: https://github.com/shahcompbio/shahcompbio.github.io.git
  target_branch: master
  fqdn: shahlab.ca
